### PR TITLE
Link Component: Handling mailto:, sms: and tel: links

### LINKED ISSUE #667: The `Link` component tries to fetch links that start with `mailto:`
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

When the Link component is rendered with an `href` value that starts with `mailto:`, the browser should open a window to send an email if you click it and nothing else.

**Observed behavior**

If you set `state.theme.autoPrefetch` to `all`, `in-view` or `hover`, an error in the console will appear as soon as Frontity tries to fetch the email link ("no handler was found for the given link").  

**Possible solution**

The check to know if the link should be fetched or not is done in this line:

https://github.com/frontity/frontity/blob/94772c1217b4c48d67bcac742ecd9c93739c73ac/packages/components/link/index.tsx#L81-L83

We should change it to return also for links that start with `mailto`, `tel` and `sms`, e.g. changing the way `isExternal` is computed:

https://github.com/frontity/frontity/blob/94772c1217b4c48d67bcac742ecd9c93739c73ac/packages/components/link/index.tsx#L69

### PR DESCRIPTION
**Pull request by nicholasio**
**What**:

Fixes #667 

**Why**:

The Link component does not handle mailto:, SMS: and tel: links properly.

**How**:

Checking if the links starts with mailto, SMS and tel in a new `isExternalUrl` function.

**Tasks**:

- [x] Code
- [x] TSDocs
- [x] TypeScript
- [x] Unit tests
- [x] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Unrelated Tasks**

- [ ] TypeScript tests
- [ ] Update starter themes
- [ ] Update other packages
- [ ] Open an issue for this feature in the [docs repo](https://github.com/frontity/docs/wiki/Code-Releases)
- [ ] Update community discussions
- [ ]  End to end tests

**Additional Comments**

### CODE REVIEW

File: packages/components/link/utils.ts [hunk 1]
```diff
@@ -137,3 +139,39 @@ export const removeSourceUrl = (
...
+ * @param link - The link Url.
+ *
+ * @returns True if the link is an external Url.
+ */
+export const isExternalUrl = (link: string) => {
+  return (
+    link.startsWith("http") ||
+    link.startsWith("mailto") ||
+    link.startsWith("tel") ||
+    link.startsWith("sms")
```
Comment (cristianbote) [inline packages/components/link/utils.ts]: Hi @nicholasio thank you so much for taking the time and open this PR. Much appreciate it!

While looking at the changes was thinking if we maybe should approach it the other way around. Meaning, instead of checking that the url starts with a certain protocol, check if the url does not start with `/`?

Comment (luisherranz) [reply packages/components/link/utils.ts]: That's a good idea. I remember that we used links like `whatsapp://send?text=xxx` for the social media apps.

But instead of checking for `/`, why don't we check that there is a protocol? That way it will work for relative links as well.

We could use either a regexp or `new URL` for that:

```js
const isExternal = (link) => {
  try {
    new URL(link);
    return true;
  } catch (e) {
    return false;
  }
};
```

```js
const isExternal = (link) => /\w+:\/\//.test(link);
```

Comment (cristianbote) [reply packages/components/link/utils.ts]: Uh! @luisherranz that's so much better. Love it! 😃 I think the `URL` try/catch will do, but as you said either works. 👍

Comment (nicholasio) [reply packages/components/link/utils.ts]: Definitely makes more sense to check this way, I'll get this updated 👍

Comment (nicholasio) [reply packages/components/link/utils.ts]: Updated!

**Comment by luisherranz** [comment]
@cristianbote can you review this one? 🙂

**Review by cristianbote — APPROVED** [review]
> @cristianbote can you review this one? 🙂

More than happy to! 👍  Great work @nicholasio! Thank you for your contribution. Looks great!

**Comment by cristianbote** [comment]
@nicholasio was waiting for the eslint and task completed checker, but I believe these are fine. Gonna look into it. But it's all good 👍

**Comment by cristianbote** [comment]
🎉  awesome job @nicholasio! Thank you!
