### PR TITLE
Use a relative path with non-external redirections

### LINKED ISSUE #728: Redirections don't send you to localhost while running Frontity in dev mode
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

If you visit a URL that is redirected, and that redirection is not to an external domain, it should maintain the same domain and just change the rest of the URL.
url
For example, the following data object:

```ts
state.source.data["/old-post/"] = {
  isFetching: false,
  isReady: true,
  isRedirection: true,
  is301: true,
  redirectionStatus: 301,
  location: "/new-post/",
}
```

should redirect you from http://localhost:3000/old-post/ to http://localhost:3000/new-post/.

**Observed behavior**

It uses the value of `state.frontity.url`, i.e. the domain of the Frontity site in production.

So, for example, if `state.frontity.url` is `https://my.frontity.site`, then Frontity redirects you from http://localhost:3000/old-post/ to https://my.frontity.site/new-post/.

**Possible solution**

After consulting the [Koa documentation](https://koajs.com/#response-redirect-url-alt-), the [Location header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location#directives) docs from MDN (even the [HTTP](https://tools.ietf.org/html/rfc7231#page-68) standard), I've concluded it is safe to use a relative URL as the Location header.

We could just remove [this line](https://github.com/frontity/frontity/blob/dev/packages/tiny-router/src/actions.ts#L255) and it would work as expected, also in the production environment.

### PR DESCRIPTION
**Pull request by DAreRodz**
**What**:

Turn the absolute URL included in the `location` prop of data objects into a relative URL, just for non external redirections (i.e. links pointing to the same domain).

**Why**:

To fix https://github.com/frontity/frontity/issues/728.

**How**:

Removing the line that was adding `state.frontity.url` to the generated redirection URL.

**Tasks**:

- [x] Code
- [x] Unit tests
- [x] End to end tests
- [x] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Unrelated Tasks**

- [ ] TSDocs
- [ ] TypeScript
- [ ] TypeScript tests
- [ ] Update starter themes
- [ ] Update other packages
- [ ] Update community discussions

**Additional Comments**

### CODE REVIEW

File: e2e/packages/redirections/src/index.tsx [hunk 1]
```diff
@@ -169,6 +169,10 @@ const redirections: Redirections = {
           state.source.redirections = query.redirections;
         }
 
+        if (state.frontity.options.url) {
+          state.frontity.url = state.frontity.options.url;
```
Comment (michalczaplinski) [inline e2e/packages/redirections/src/index.tsx:173]: nice trick. I worry sometimes that the Frontity Options can be an attack vector if someone (god forbid) `evals` the contents of a frontity option or passes it as a parameter to a `fetch()` call etc.

I ll ping DevRel to explicitly warn about this in the docs.

**Review by michalczaplinski — APPROVED** [review]
Great! 👍 Thanks @DAreRodz! 🙂

File: e2e/packages/redirections/src/index.tsx (hunk 1 above)
Comment (DAreRodz) [reply e2e/packages/redirections/src/index.tsx:173]: Good idea :+1:
