### PR TITLE
analytics, router, yoast: Fix type inconsistencies and incorrect imports

### LINKED ISSUE #307: Fix TS type inconsistencies
There are several TS inconsistencies that were discovered while working on #306 .

They affect the `tiny-router`, `yoast` and `source.

### PR DESCRIPTION
**Pull request by michalczaplinski**
#### Description of what you did:
There were some TS inconsistencies that were introduced recently while updating the types of `Source` and `Data`:
- Outdated imports
- incorrect type inference and assertions

fixes: #307 

#### My PR is a:
- 🐞 Bug fix

#### Is the PR ready to be merged?

- ✅ Yes!

### CODE REVIEW

File: packages/yoast/src/state/utils.ts [hunk 1]
```diff
@@ -1,11 +1,28 @@
...
-export type Entity = (Author | Taxonomy | PostType | Attachment) & {
+export type Entity = (
+  | AuthorEntity
+  | TaxonomyEntity
+  | PostType
+  | AttachmentEntity) & {
   yoast_meta: YoastMeta;
 };
 
-export const getEntity = ({ state, data }): Entity => {
```
Comment (michalczaplinski) [inline packages/yoast/src/state/utils.ts:8]: Better to just assert the types of `state` and `data` and let the TS type inference do the magic 😅

**Comment by michalczaplinski** [comment]
https://overreacted.io/fix-like-no-ones-watching/  ✌️

**Review by luisherranz — APPROVED** [review]
I'm sorry that you worked on the yoast package because it was deprecated in favor of head-tags. I've fixed that in this PR: https://github.com/frontity/frontity/pull/310

The rest is fine, thanks @michalczaplinski for the fixes.
