### PR TITLE
fix(core): return 404 if HMR endpoint gets through Webpack to Frontity

### LINKED ISSUE #141: Getting an error while building the project
Run `npx frontity build && npx frontity` serve on your frontity project

Expected: 
No errors while serving the website.

Actual: 
Screenshot 2019-06-26 at 3 36 40 PM

Other than that website is served well without any problem

### PR DESCRIPTION
**Pull request by luisherranz**
Fixes https://github.com/frontity/frontity/issues/141.

#### Description of what you did:

When you switch from `dev` to `build && serve` and leave an open browser, it tries to connect to `/__webpack_hmr` for HMR and that results in an error in the console.

This PR adds an ignore for that url.

#### My PR is a:

- [x] 🐞 Bug fix
- [ ] 🚀 New feature
- [ ] 🔝 Improvement

#### Main update on the:

- [ ] Documentation
- [x] Framework

#### Is the PR ready to be merged?

- [x] Yes!
- [ ] Work in progress

### CODE REVIEW

File: packages/core/src/server/index.tsx [hunk 1]
```diff
@@ -35,6 +35,14 @@ export default ({ packages }) => {
     })
   );
 
+  // Ignore HRM if not in dev mode or old browser open.
```
Comment (DAreRodz) [inline packages/core/src/server/index.tsx]: Just a typo in this comment 🙈

Comment (luisherranz) [reply packages/core/src/server/index.tsx]: Fixed.

**Review by orballo — APPROVED** [review]
