### PR TITLE
Core: fix yarn symlink bug

### LINKED ISSUE #364: Yarn isn't working [8pt]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**
Users expect to be able to use `yarn` instead of `npm`.

**Observed behavior**
`yarn` is not working because it doesn’t install local dependencies using `symlinks`. It copies the folder instead.

**Possible solution**
We can use `symlink-dir` at `frontity dev`.

### PR DESCRIPTION
**Pull request by iamuchejude**
**What**:

Yarn install local dependencies using symlinks. It copies the folder instead. See #364 

**How**:

Apply the [`symlink`](https://www.npmjs.com/package/symlink-dir) to folders when you run `frontity dev`

**Tasks**:

- [x] Code
- ~[ ] TypeScript~

- [x] Unit tests
- ~[ ] End to end tests~
- ~[ ] TypeScript tests~

- ~[ ] Update starter themes~
- ~[ ] Update other packages~

- ~[ ] Documentation~
- ~[ ] Community discussions~

- [x] Changeset

### CODE REVIEW

File: packages/core/src/scripts/utils/create-symlinks.ts [hunk 1]
```diff
@@ -26,7 +30,7 @@ export default async () => {
     dependencyNames.map(async (name) => {
       const packageDir = dependencies[name].replace(/^(file:)/, "");
 
-      const dir = await resolve(process.cwd(), packageDir);
+      const dir = resolve(process.env.CWD, packageDir);
```
Comment (michalczaplinski) [inline packages/core/src/scripts/utils/create-symlinks.ts:33]: @iamuchejude I've changed this ⬆️ 

Because I set the `process.env.CWD` in the test I can "mock" that we are running the command in a fake project directory (which is really just a temp dir). But make sure that it still works when you test manually 😀

Comment (iamuchejude) [reply packages/core/src/scripts/utils/create-symlinks.ts:33]: Oh cool!

File: packages/core/src/scripts/utils/__tests__/create-symlinks.test.ts [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+          }
+        }`,
+      [`${projectDir}/packages/dep-with-file`]: {
+        "package.json": `{ name: "dep-with-file" }`,
+      },
+    });
+
+    await createSymlinks();
+
+    const stats = await lstatPromise("./node_modules/dep-with-file");
```
Comment (michalczaplinski) [inline packages/core/src/scripts/utils/__tests__/create-symlinks.test.ts]: There is also [`lstatSync`](https://nodejs.org/api/fs.html#fs_fs_lstatsync_path_options) by the way, that I think would be better to use instead I realized, but it's not too important 🙂

File: packages/core/src/scripts/utils/__tests__/create-symlinks.test.ts [hunk 3]
```diff
@@ -0,0 +1,107 @@
...
+          "${packageName}": "file:./packages/${packageName}"
+        }
+      }`,
+    });
+
+    try {
+      await createSymlinks();
+    } catch (e) {
+      expect(true).toBeTruthy();
+    }
```
Comment (michalczaplinski) [inline packages/core/src/scripts/utils/__tests__/create-symlinks.test.ts]: Why do we need this? 🙂

File: packages/core/src/scripts/utils/__tests__/create-symlinks.test.ts (hunk 2 above)
Comment (michalczaplinski) [reply packages/core/src/scripts/utils/__tests__/create-symlinks.test.ts]: You don't have to change it, just a comment :)

File: packages/core/src/scripts/utils/__tests__/create-symlinks.test.ts (hunk 3 above)
Comment (iamuchejude) [reply packages/core/src/scripts/utils/__tests__/create-symlinks.test.ts]: Oh, I was supposed to get rid of this.

**Review by michalczaplinski — APPROVED** [review]

File: packages/core/package.json [hunk 4]
```diff
@@ -61,6 +61,7 @@
     "koa-static": "^5.0.0",
     "lodash-es": "^4.17.11",
     "minimist": "^1.2.5",
+    "mock-fs": "^4.12.0",
```
Comment (luisherranz) [inline packages/core/package.json:64]: I think this should be on `devDependencies`, right?
