### PR TITLE
Amend getMatch to work with a source object instead

### LINKED ISSUE #596: `actions.source.fetch` fails with links with query params for certain handlers [5pt]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

Let's say we have these two handlers, one for `movie` entities and another for `movie` attachments:
```ts
[
  {
    pattern: "/movie/:movieSlug/:slug",
    name: "movie attachment",
    func: () => { ... },
    priority: 10,
  },
  {
    pattern: "/movie/:slug",
    name: "movie",
    func: () => { ... },
    priority: 10,
  },
]
```

**Expected behavior**

When doing
```ts
actions.source.fetch("/movie/the-terminator/?query=string")
```

you may expect that the `movie` handler is the one that matches.

**Observed behavior**

It is not only that the `movie attachment` handler is matched but also the `getMatch()` call fails because the params that `getMatch()` returns are extracted from the pathname and not from the query, which [is being removed](https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/libraries/get-match.ts#L20-L22) before getting those params, thus making the link not to match anymore with the matched pattern from `movie attachment` and throwing the following error in this line:
 and the following error is thrown (in [this line](https://github.com/frontity/frontity/blob/dev/packages/wp-source/src/libraries/get-match.ts#L24)):

```
TypeError: Cannot read property 'slice' of null
```
The data object for that link ends being:

```ts
{
  isFetching: true,
  isReady: false,
  link: "/movie/the-terminator/?query=string",
  page: 1,
  query: { query: "string" },
  route: "/movie/the-terminator/",
}
```

**Steps involved to reproduce the problem**

1. `npx frontity create`.
2. Add the handlers mentioned above to `libraries.source.handlers` in /packages/mars-theme/index.js
3. Add the link `"/movie/the-terminator/?query=string"` to the menu in /frontity.settings.js
4. `npx frontity dev` and click on that link.
4. In the console you will see `TypeError: Cannot read property 'slice' of null`.
5. The theme will just show the loading bar.

**Possible solution**

I'm not sure how to solve this, actually.

As a workaround, users just would have to add a trailing slash to their handler patterns.

### PR DESCRIPTION
**Pull request by cristianbote**
**What**:

Change the way `getMatch` was handling the `link` to pattern match.

**Why**:

Matching was not happening for urls with querystring params.

**How**:

Different codepath for patterns that are defined using regexp, since the queryparams can only be parsed with regular expressions.

**Tasks**:

- [x] Code
- [x] TSDocs
- [x] TypeScript
- [x] Unit tests
- [x] TypeScript tests
- [x] Update community discussions
- [x] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Unrelated Tasks**

- [ ] End to end tests
- [ ] Update starter themes
- [ ] Update other packages
- [ ] Open an issue for this feature in the [docs repo](https://github.com/frontity/docs/wiki/Code-Releases)

**Additional Comments**

### CODE REVIEW

File: packages/wp-source/src/libraries/get-match.ts [hunk 1]
```diff
@@ -56,10 +56,30 @@ interface GetMatchReturn<
...
+ * The `source` object that contains a link and a route.
+ */
+interface Source {
+  /**
+   * The full link with `queryString`.
+   */
+  link?: string;
+
+  /**
+   * The link without the query part. Also known as the pathname.
```
Comment (luisherranz) [inline packages/wp-source/src/libraries/get-match.ts]: There is no need to change the TSDocs because it's not a big deal, but just to make it clear, the route is not the pathname but the pathname without the pagination: 

- link: `/category/some-category/page/3?a=1`
- pathname: `/category/some-category/page/3`
- route: `/category/some-category/`

We didn't find a better name for that so we used `route` 😆🤷

Comment (cristianbote) [reply packages/wp-source/src/libraries/get-match.ts]: Totally 😅 . We'll keep this in mind on next source version and we'll name it better.

Comment (luisherranz) [reply packages/wp-source/src/libraries/get-match.ts]: > We'll keep this in mind on next source version and we'll name it better.

It's open to suggestions 👍

**Review by luisherranz — APPROVED** [review]
Great work, thanks Cristian! 👏🙂
